import Head from "next/head";
import MainLayout from "@/components/MainLayout";
import { Col, Row } from "antd";
import Content from "@/components/Content";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Row gutter={[30, 30]}>
          <Col xs={12}>
            <Content>Content</Content>
          </Col>
          <Col xs={12}>
            <Content>Content</Content>
          </Col>
          <Col xs={24} flex={1}>
            <Content>Content</Content>
          </Col>
        </Row>
      </MainLayout>
    </>
  );
}
